### ISSUE TITLE
MiddlewareError: Type generator exists in middleware but is missing in Schema.

### ISSUE THREAD

**Issue by talentlessguy** [dimatill/graphql-shield#1350]
# Bug report

- [x] I have checked other issues to make sure this is not a duplicate.

there are a few similar issues but they were closed without any solution:

- https://github.com/maticzav/graphql-shield/issues/970
- https://github.com/maticzav/graphql-shield/issues/151#issuecomment-428368605

## Describe the bug

```
file:///home/v1rtl/Coding/x/api/node_modules/.pnpm/graphql-middleware@6.1.11_graphql@15.0.0/node_modules/graphql-middleware/dist/validation.mjs:10
      throw new MiddlewareError(`Type ${type} exists in middleware but is missing in Schema.`);
            ^

MiddlewareError: Type generator exists in middleware but is missing in Schema.
    at file:///home/v1rtl/Coding/x/api/node_modules/.pnpm/graphql-middleware@6.1.11_graphql@15.0.0/node_modules/graphql-middleware/dist/validation.mjs:10:13
    at Array.forEach (<anonymous>)
    at validateMiddleware (file:///home/v1rtl/Coding/x/api/node_modules/.pnpm/graphql-middleware@6.1.11_graphql@15.0.0/node_modules/graphql-middleware/dist/validation.mjs:8:27)
    at addMiddlewareToSchema (file:///home/v1rtl/Coding/x/api/node_modules/.pnpm/graphql-middleware@6.1.11_graphql@15.0.0/node_modules/graphql-middleware/dist/middleware.mjs:8:27)
    at normalisedMiddlewares.reduceRight.schema.schema (file:///home/v1rtl/Coding/x/api/node_modules/.pnpm/graphql-middleware@6.1.11_graphql@15.0.0/node_modules/graphql-middleware/dist/middleware.mjs:36:9)
    at Array.reduceRight (<anonymous>)
    at applyMiddlewareWithOptions (file:///home/v1rtl/Coding/x/api/node_modules/.pnpm/graphql-middleware@6.1.11_graphql@15.0.0/node_modules/graphql-middleware/dist/middleware.mjs:29:77)
    at applyMiddleware (file:///home/v1rtl/Coding/x/api/node_modules/.pnpm/graphql-middleware@6.1.11_graphql@15.0.0/node_modules/graphql-middleware/dist/middleware.mjs:51:10)
    at file:///home/v1rtl/Coding/x/api/graphql/schema.ts:23:17
    at ModuleJob.run (node:internal/modules/esm/module_job:183:25)
```

## To Reproduce

```ts
import { makeExecutableSchema } from '@graphql-tools/schema'
import { applyMiddleware } from 'graphql-middleware'
import { shield, rule } from 'graphql-shield'
import { gql } from 'graphql-tag'

// Construct a schema, using GraphQL schema language.
let typeDefs = gql`
  type Query {
    hello: String
  }
`

const resolvers = {
  Query: {
    hello: () => 'Hello world!'
  }
}

const permissions = shield({
  Query: {
    hello: rule()(async () => {
      return false
    })
  }
})

const _schema = applyMiddleware(
  makeExecutableSchema({
    typeDefs,
    resolvers
  }),
  permissions
)

export const schema = applyMiddleware(_schema, permissions)
```

```json
{
  "name": "api",
  "type": "module",
  "dependencies": {
    "@graphql-tools/schema": "^8.3.1",
    "graphql": "15.0.0",
    "graphql-middleware": "^6.1.11",
    "graphql-shield": "^7.5.0",
    "graphql-tag": "^2.12.5"
  },
  "devDependencies": {
    "@types/node": "^16.11.6",
    "tsm": "^2.1.4"
  }
}
```

```sh
$ tsm index.ts
```

## Environment

- Node.js 16.11
- Linux x64
- pnpm 6.17.2

**Comment by wangel13** [comment]
I think it's connected with https://github.com/maticzav/graphql-middleware/issues/433 and you can downgrade `graphql-middleware` to =6.0.9 to make it work.
